### ISSUE TITLE
How to Scrape 538 Data

### ISSUE THREAD

**Issue by srnicholson** [jacktose/PI-vs-538#3]
You can scrape 538 election forecast data in JSON format using the following syntax:

`https://projects.fivethirtyeight.com/2016-election-forecast/{STATE ABBREV}.json`

Example for Colorado:
[https://projects.fivethirtyeight.com/2016-election-forecast/CO.json](https://projects.fivethirtyeight.com/2016-election-forecast/CO.json)

[Here's a quick-n-dirty Excel version](https://github.com/srnicholson/PI-538)

**Comment by jacktose** [comment]
YES! Thank you. All my googling did not turn that up somehow.

Out of curiosity, how did you happen upon my little project?

**Comment by jacktose** [comment]
Alright, changed it to scrape from 538 API, too. Much nicer and more useful. Thanks again!

**Comment by srnicholson** [comment]
Glad to help! I stumbled upon your project while browsing around repositories involving 538 and noticed that yours was something very similar to what i had done.

Happy coding!

**Comment by jacktose** [comment]
You too!
